// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYNDZogFgAsEfjmIGZGNF8NQAcD0DE1I',
    appId: '1:104689228786:web:f0cf217ae1f9aec49f696b',
    messagingSenderId: '104689228786',
    projectId: 'myapp-aa104',
    authDomain: 'myapp-aa104.firebaseapp.com',
    storageBucket: 'myapp-aa104.appspot.com',
    measurementId: 'G-JE0TL5JN7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQvMOOygVvo-XcxZh-3u9dub2FbcqGTo',
    appId: '1:104689228786:android:d1ad1193df00a4ef9f696b',
    messagingSenderId: '104689228786',
    projectId: 'myapp-aa104',
    storageBucket: 'myapp-aa104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrG_rSyN93mja4u0Zuyx1WQMDIhKER74k',
    appId: '1:104689228786:ios:03811ac3875e9f149f696b',
    messagingSenderId: '104689228786',
    projectId: 'myapp-aa104',
    storageBucket: 'myapp-aa104.appspot.com',
    iosBundleId: 'com.example.logapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrG_rSyN93mja4u0Zuyx1WQMDIhKER74k',
    appId: '1:104689228786:ios:0bea71fd25d781479f696b',
    messagingSenderId: '104689228786',
    projectId: 'myapp-aa104',
    storageBucket: 'myapp-aa104.appspot.com',
    iosBundleId: 'com.example.logapp.RunnerTests',
  );
}
